export const SUBACCOUNT_CREATE_REQUEST = "SUBACCOUNT_CREATE_REQUEST";
export const SUBACCOUNT_CREATE_SUCCESS = "SUBACCOUNT_CREATE_SUCCESS";
export const SUBACCOUNT_CREATE_FAIL = "SUBACCOUNT_CREATE_FAIL";
export const SUBACCOUNT_CREATE_RESET = "SUBACCOUNT_CREATE_RESET";

export const SUBACCOUNT_LIST_REQUEST = "SUBACCOUNT_LIST_REQUEST";
export const SUBACCOUNT_LIST_SUCCESS = "SUBACCOUNT_LIST_SUCCESS";
export const SUBACCOUNT_LIST_FAIL = "SUBACCOUNT_LIST_FAIL";
export const SUBACCOUNT_LIST_RESET = "SUBACCOUNT_LIST_RESET";

export const SUBACCOUNT_DELETE_REQUEST = "SUBACCOUNT_DELETE_REQUEST";
export const SUBACCOUNT_DELETE_SUCCESS = "SUBACCOUNT_DELETE_SUCCESS";
export const SUBACCOUNT_DELETE_FAIL = "SUBACCOUNT_DELETE_FAIL";

export const SUBACCOUNT_UPDATE_REQUEST = "SUBACCOUNT_UPDATE_REQUEST";
export const SUBACCOUNT_UPDATE_SUCCESS = "SUBACCOUNT_UPDATE_SUCCESS";
export const SUBACCOUNT_UPDATE_FAIL = "SUBACCOUNT_UPDATE_FAIL";
export const SUBACCOUNT_UPDATE_RESET = "SUBACCOUNT_UPDATE_RESET";

export const SUBACCOUNT_DETAILS_REQUEST = "SUBACCOUNT_DETAILS_REQUEST";
export const SUBACCOUNT_DETAILS_SUCCESS = "SUBACCOUNT_DETAILS_SUCCESS";
export const SUBACCOUNT_DETAILS_FAIL = "SUBACCOUNT_DETAILS_FAIL";
export const SUBACCOUNT_DETAILS_RESET = "SUBACCOUNT_DETAILS_RESET";
